/*
 * aboutFrame.java
 *
 * Created on 18-Apr-2011, 09:12:05
 */

package stegsolve;

/**
 * Just a small about box with some details of the
 * application
 *
 * @author Caesum
 */
public class AboutFrame extends javax.swing.JFrame {

    /**
     * Creates new form aboutFrame
     */
    public AboutFrame() {
        initComponents();
        jEditorPane1.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        aboutPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okButton.setText("确定");
        okButton.setAlignmentX(0.5F);
        okButton.addActionListener(this::okButtonActionPerformed);

        aboutPanel.setPreferredSize(new java.awt.Dimension(450, 300));

        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jEditorPane1.setText("<html>\n<center><b>Stegsolve v1.5 由 Souno Inherited 在 Caesum 中继承<br>由 Giotino 修改</b></center>\n<br>\nStegsolve 是一个用于解决挑战的隐写术解算器。它提供了以下主要功能：\n<ul>\n<li>快速查看不同的位平面和一些简单的变换。</li>\n<li>从平面提取数据。这可以是行顺序或列顺序，将位作为位流处理并转换为字节。</li>\n<li>对文件格式进行一些简单的检查，并报告文件大小、附加字节、文件空洞等。这在很大程度上取决于图像的类型。</li>\n<li>立体图解算器 - 只需改变偏移量，直到图像变得可见。</li>\n<li>用于动画图像的帧浏览器。这也应该适用于查看多层PNG文件中的层。</li>\n<li>图像合成器，用于以各种方式合并两个图像，并浏览不同的组合。</li>\n</ul>\n<p>可以使用CTRL-C复制、CTRL-V粘贴和CTRL-X剪切从大多数文本中复制/剪切和粘贴。\n<p>如果一个图像无法加载，例如因为它是损坏的，那么文件分析仍然会打开你刚才试图查看的文件。然而，它可能会在报告你想知道的信息之前崩溃。不过，这对于PNG的CRC值被破坏的图像来说是有效的。\n</html>\n");
        jEditorPane1.setMinimumSize(new java.awt.Dimension(150, 150));
        jEditorPane1.setPreferredSize(new java.awt.Dimension(150, 150));
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
                aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        aboutPanelLayout.setVerticalGroup(
                aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(okButton)
                                .addContainerGap(227, Short.MAX_VALUE))
                        .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okButton)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Disposes of the form when the ok button is pressed
     *
     * @param evt Button event
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
